apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  #googleCloudBuild:
  #  projectId: ticketing-dev-373717
  artifacts:
    - image: rabihmaj/auth  #us.gcr.io/ticketing-dev-373717/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rabihmaj/client  #us.gcr.io/ticketing-dev-373717/auth
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: rabihmaj/tickets  #us.gcr.io/ticketing-dev-373717/auth
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rabihmaj/orders  #us.gcr.io/ticketing-dev-373717/auth
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rabihmaj/expiration  #us.gcr.io/ticketing-dev-373717/auth
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rabihmaj/payment  #us.gcr.io/ticketing-dev-373717/auth
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .