name: tests-payments

on:
  pull_request
    paths:
      - 'payments/**' #only if the changes are inside the payments folder
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
