name: tests-orders

on:
  pull_request
    paths:
      - 'orders/**' #only if the changes are inside the orders folder
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
